### ISSUE TITLE
getting error While running scripts/plot-opo.py : FileNotFoundError: [Errno 2] No such file or directory: 'pdfcrop': 'pdfcrop'

### ISSUE THREAD

**Issue by AshutoshUpadhya** [lukehsiao/lctes-p27#2]
I am getting Error while running Plot-opo.py ? Any idea how can I generate this file as I followed al the steps sequentially as per READ.md

Error : 
/lctes-p27/scripts$ python plot_opo.py
[2019-11-24 23:57:31,488][INFO] __main__:67 - gain_b = 0.75, current_b = 0.75
[2019-11-24 23:57:31,508][INFO] __main__:86 - len(matched): 2028
[2019-11-24 23:57:31,508][INFO] __main__:88 - Plotting from ../hack/opamps/data/opo_processed_opamps.csv...
Traceback (most recent call last):
  File "plot_opo.py", line 179, in <module>
    args.cb,
  File "plot_opo.py", line 118, in _plot
    run(["pdfcrop", outfile, outfile], stdout=DEVNULL, check=True)
  File "/softwares/anaconda3/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/softwares/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/softwares/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pdfcrop': 'pdfcrop'

Thanks in advance

**Comment by AshutoshUpadhya** [comment]
Got the solution my self. Just did:
sudo apt-get install texlive-extra-utils
